### PR TITLE
Warning for the order of plugins using PrefetchServiceWorker

### PR DESCRIPTION
**Pull request by tzdesign**
@wmertens I added a warning.
My question while writing this was, can't we change qwik to create this file earlier?

This is dangerous if you think about the whole plugin structure and the extensibility of qwik, right?

### CODE REVIEW

**Comment by wmertens** [comment]
Actually we should document the reverse, the plugin should always be last except for qwik < 1.8.

Now that I think about it I wonder why it was needed before 1.8. I'm pretty sure it didn't work but I'm not sure why :sweat:. As long as the imports are detected it can do the transform (so before or after qwik runs), and then it needs to do the replacements as the very last step of the build.

**Comment by tzdesign** [comment]
@wmertens sorry for the late response, we had a bit of a chaos the last weeks 🦀 

I would go to save here. I flipped the order to the new one and we can continue telling people to use the old order when using <1.8.

See commit 733a192

**Comment by tzdesign** [comment]
@wmertens this should fix the warning:
image

**Review by wmertens — APPROVED** [review]
LGTM

**Comment by wmertens** [comment]
@tzdesign all of this is merged via the other PR, right?

**Pull request closed without merging**
